### ISSUE TITLE
請問資料最終是怎麼分散到

### ISSUE THREAD

**Issue by vlike** [matishsiao/ssdbproxy#1]
HI
看了你的網站，上面寫道：

> 寫入資料：寫入資料會優先寫入到第一個node,這樣在熱查詢的時候會加快找到資料的速度

當資料寫入第一個node後，就一直放在那裏嗎？如果有多個分片，資料會怎樣分散到其之上？

此proxy會有繼續開發的計劃嗎？

**Comment by matishsiao** [comment]
寫進第一個node 後資料就會一直在那
我沒有做分片 ，因為會需要維護index
未來還是會維護
