### ISSUE TITLE
will GET check every node ?

### ISSUE THREAD

**Issue by ss3ds** [matishsiao/ssdbproxy#2]
is that it ? checking every node to know where it is ?

and merging sets ?

**Comment by matishsiao** [comment]
yes, if you get data, it will checking every node and merging sets.

**Comment by ss3ds** [comment]
so, what's the benefit from use this proxy ?

**Comment by matishsiao** [comment]
Benefit:
1.SSDB not support zip 
2.SSDB replication out sync
3.SSDB not support sharding
